# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-14 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='p_hobby',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
