# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0002_auto_20200317_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='id_person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='five.Person'),
        ),
    ]
